from qtile_extras.popup import toolkit as popup
from utils import COLORSCHEME

battery_layout = popup.PopupAbsoluteLayout(
    width=400,
    height=120,
    controls=[
        popup.PopupText(
            name="icon",
            font="Symbols Nerd Font",
            fontsize=25,
            foreground=COLORSCHEME["TEXT"],
            pos_x=20,
            pos_y=40,
            width=20,
            height=20,
            h_align="center",
        ),
        popup.PopupText(
            name="percentage",
            font="Iosevka Etoile Bold",
            fontsize=18,
            foreground=COLORSCHEME["TEXT"],
            pos_x=45,
            pos_y=40,
            width=70,
            height=20,
            h_align="center",
        ),
        popup.PopupText(
            name="charging",
            font="Iosevka Slab",
            fontsize=14,
            foreground=COLORSCHEME["SUBTEXT 1"],
            pos_x=125,
            pos_y=60,
            width=240,
            height=20,
            h_align="center",
        ),
        popup.PopupSlider(
            name="value",
            bar_size=8,
            marker_size=0,
            marker_colour=COLORSCHEME["TEXT"],
            colour_below=COLORSCHEME["GREEN"],
            colour_above=COLORSCHEME["SURFACE 0"],
            bar_border_colour=COLORSCHEME["TEXT"],
            pos_x=120,
            pos_y=40,
            height=20,
            width=260,
        ),
    ],
    background=COLORSCHEME["MANTLE"],
    close_on_click=True,
)
