from qtile_extras.popup import toolkit as popup
from utils import COLORSCHEME

volume_layout = popup.PopupAbsoluteLayout(
    width=400,
    height=220,
    controls=[
        popup.PopupText(
            name="out_icon",
            font="Symbols Nerd Font",
            fontsize=25,
            foreground=COLORSCHEME["TEXT"],
            pos_x=20,
            pos_y=40,
            width=30,
            height=20,
            h_align="center",
        ),
        popup.PopupText(
            name="out_percent",
            font="Iosevka Etoile Bold",
            fontsize=18,
            foreground=COLORSCHEME["TEXT"],
            pos_x=45,
            pos_y=40,
            width=70,
            height=20,
            h_align="center",
        ),
        popup.PopupText(
            name="out_mode",
            font="Iosevka Slab",
            fontsize=14,
            foreground=COLORSCHEME["SUBTEXT 1"],
            pos_x=125,
            pos_y=60,
            width=240,
            height=20,
            h_align="center",
        ),
        popup.PopupSlider(
            name="out_value",
            bar_size=8,
            marker_size=12,
            marker_colour=COLORSCHEME["TEXT"],
            colour_below=COLORSCHEME["MAUVE"],
            colour_above=COLORSCHEME["SURFACE 0"],
            bar_border_colour=COLORSCHEME["TEXT"],
            pos_x=120,
            pos_y=40,
            height=20,
            width=260,
            can_focus=True,
            highlight=COLORSCHEME["MANTLE"],
            # drag_callback=drag_callback,
        ),
        popup.PopupText(
            name="in_icon",
            font="Symbols Nerd Font",
            fontsize=25,
            foreground=COLORSCHEME["TEXT"],
            pos_x=20,
            pos_y=140,
            width=30,
            height=20,
            h_align="center",
        ),
        popup.PopupText(
            name="in_percent",
            font="Iosevka Etoile Bold",
            fontsize=18,
            foreground=COLORSCHEME["TEXT"],
            pos_x=45,
            pos_y=140,
            width=70,
            height=20,
            h_align="center",
        ),
        popup.PopupText(
            name="in_mode",
            font="Iosevka Slab",
            fontsize=14,
            foreground=COLORSCHEME["SUBTEXT 1"],
            pos_x=125,
            pos_y=160,
            width=240,
            height=20,
            h_align="center",
        ),
        popup.PopupSlider(
            name="in_value",
            bar_size=8,
            marker_size=12,
            marker_colour=COLORSCHEME["TEXT"],
            colour_below=COLORSCHEME["MAUVE"],
            colour_above=COLORSCHEME["SURFACE 0"],
            bar_border_colour=COLORSCHEME["TEXT"],
            pos_x=120,
            pos_y=140,
            height=20,
            width=260,
            can_focus=True,
            highlight=COLORSCHEME["MANTLE"],
            # drag_callback=drag_callback,
        ),
    ],
    background=COLORSCHEME["MANTLE"],
    initial_focus=3,
    close_on_click=False,
)
